language: python

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

cache: pip

python:
  - "3.6"
  - "3.7"

addons:
  apt:
    update: true
    packages:
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
  homebrew:
    update: true
    packages:
      - gmp
      - mpfr
      - libmpc

before_script:
  - python3 -m tmtoolkit setup test

script:
  - pytest
