language: python
dist: bionic

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -y install libgmp-dev libmpfr-dev libmpc-dev python3-venv
addons:
  apt:
    update: true

install:
  - python3 -m venv testenv
  - source testenv/bin/activate
  - pip install -U pip
  - pip install -U tox

script:
  - tox -re py36-full-datatable
  - tox -re py37-full-datatable
